# Generated by Django 3.0.5 on 2020-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_driverlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlist',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
