# Generated by Django 3.0.5 on 2020-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0006_auto_20200505_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlist',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
